//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrator.ServiceAdministrator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaKnjiga", Namespace="http://schemas.datacontract.org/2004/07/IST_Projekat2", ItemName="Knjiga")]
    [System.SerializableAttribute()]
    public class ListaKnjiga : System.Collections.Generic.List<Administrator.ServiceAdministrator.Knjiga> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Knjiga", Namespace="http://schemas.datacontract.org/2004/07/IST_Projekat2")]
    [System.SerializableAttribute()]
    public partial class Knjiga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_knjigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopustField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_knjige {
            get {
                return this.Id_knjigeField;
            }
            set {
                if ((this.Id_knjigeField.Equals(value) != true)) {
                    this.Id_knjigeField = value;
                    this.RaisePropertyChanged("Id_knjige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Popust {
            get {
                return this.PopustField;
            }
            set {
                if ((this.PopustField.Equals(value) != true)) {
                    this.PopustField = value;
                    this.RaisePropertyChanged("Popust");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Porudzbina", Namespace="http://schemas.datacontract.org/2004/07/IST_Projekat2")]
    [System.SerializableAttribute()]
    public partial class Porudzbina : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_knjigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_korisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_porudzbineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_knjige {
            get {
                return this.Id_knjigeField;
            }
            set {
                if ((this.Id_knjigeField.Equals(value) != true)) {
                    this.Id_knjigeField = value;
                    this.RaisePropertyChanged("Id_knjige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_korisnika {
            get {
                return this.Id_korisnikaField;
            }
            set {
                if ((this.Id_korisnikaField.Equals(value) != true)) {
                    this.Id_korisnikaField = value;
                    this.RaisePropertyChanged("Id_korisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_porudzbine {
            get {
                return this.Id_porudzbineField;
            }
            set {
                if ((this.Id_porudzbineField.Equals(value) != true)) {
                    this.Id_porudzbineField = value;
                    this.RaisePropertyChanged("Id_porudzbine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/IST_Projekat2")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Korisnicko_imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LozinkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Korisnicko_ime {
            get {
                return this.Korisnicko_imeField;
            }
            set {
                if ((object.ReferenceEquals(this.Korisnicko_imeField, value) != true)) {
                    this.Korisnicko_imeField = value;
                    this.RaisePropertyChanged("Korisnicko_ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka {
            get {
                return this.LozinkaField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true)) {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaKorisnika", Namespace="http://schemas.datacontract.org/2004/07/IST_Projekat2", ItemName="Korisnik")]
    [System.SerializableAttribute()]
    public class ListaKorisnika : System.Collections.Generic.List<Administrator.ServiceAdministrator.Korisnik> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaPorudzbina", Namespace="http://schemas.datacontract.org/2004/07/IST_Projekat2", ItemName="Porudzbina")]
    [System.SerializableAttribute()]
    public class ListaPorudzbina : System.Collections.Generic.List<Administrator.ServiceAdministrator.Porudzbina> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdministrator.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjige", ReplyAction="http://tempuri.org/IService1/vratiKnjigeResponse")]
        Administrator.ServiceAdministrator.ListaKnjiga vratiKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjige", ReplyAction="http://tempuri.org/IService1/vratiKnjigeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKnjiga> vratiKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjigu", ReplyAction="http://tempuri.org/IService1/vratiKnjiguResponse")]
        Administrator.ServiceAdministrator.Knjiga vratiKnjigu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjigu", ReplyAction="http://tempuri.org/IService1/vratiKnjiguResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Knjiga> vratiKnjiguAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/poruciKnjigu", ReplyAction="http://tempuri.org/IService1/poruciKnjiguResponse")]
        Administrator.ServiceAdministrator.Porudzbina poruciKnjigu(int id, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/poruciKnjigu", ReplyAction="http://tempuri.org/IService1/poruciKnjiguResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> poruciKnjiguAsync(int id, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        Administrator.ServiceAdministrator.Korisnik login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> loginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Administrator.ServiceAdministrator.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Administrator.ServiceAdministrator.IService1>, Administrator.ServiceAdministrator.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Administrator.ServiceAdministrator.ListaKnjiga vratiKnjige() {
            return base.Channel.vratiKnjige();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKnjiga> vratiKnjigeAsync() {
            return base.Channel.vratiKnjigeAsync();
        }
        
        public Administrator.ServiceAdministrator.Knjiga vratiKnjigu(int id) {
            return base.Channel.vratiKnjigu(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Knjiga> vratiKnjiguAsync(int id) {
            return base.Channel.vratiKnjiguAsync(id);
        }
        
        public Administrator.ServiceAdministrator.Porudzbina poruciKnjigu(int id, int kolicina) {
            return base.Channel.poruciKnjigu(id, kolicina);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> poruciKnjiguAsync(int id, int kolicina) {
            return base.Channel.poruciKnjiguAsync(id, kolicina);
        }
        
        public Administrator.ServiceAdministrator.Korisnik login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdministrator.IServiceOperater")]
    public interface IServiceOperater {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjige", ReplyAction="http://tempuri.org/IService1/vratiKnjigeResponse")]
        Administrator.ServiceAdministrator.ListaKnjiga vratiKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjige", ReplyAction="http://tempuri.org/IService1/vratiKnjigeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKnjiga> vratiKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjigu", ReplyAction="http://tempuri.org/IService1/vratiKnjiguResponse")]
        Administrator.ServiceAdministrator.Knjiga vratiKnjigu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjigu", ReplyAction="http://tempuri.org/IService1/vratiKnjiguResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Knjiga> vratiKnjiguAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/poruciKnjigu", ReplyAction="http://tempuri.org/IService1/poruciKnjiguResponse")]
        Administrator.ServiceAdministrator.Porudzbina poruciKnjigu(int id, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/poruciKnjigu", ReplyAction="http://tempuri.org/IService1/poruciKnjiguResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> poruciKnjiguAsync(int id, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        Administrator.ServiceAdministrator.Korisnik login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/dodajKnjiguResponse")]
        void dodajKnjigu(string autor, string naziv, double cena, int popust, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/dodajKnjiguResponse")]
        System.Threading.Tasks.Task dodajKnjiguAsync(string autor, string naziv, double cena, int popust, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKnjiguResponse")]
        void izmeniKnjigu(Administrator.ServiceAdministrator.Knjiga knjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKnjiguResponse")]
        System.Threading.Tasks.Task izmeniKnjiguAsync(Administrator.ServiceAdministrator.Knjiga knjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/dodajKorisnikaResponse")]
        void dodajKorisnika(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/dodajKorisnikaResponse")]
        System.Threading.Tasks.Task dodajKorisnikaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnike", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikeResponse")]
        Administrator.ServiceAdministrator.ListaKorisnika vratiKorisnike();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnike", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKorisnika> vratiKorisnikeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKorisnikaResponse")]
        void izmeniKorisnika(Administrator.ServiceAdministrator.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKorisnikaResponse")]
        System.Threading.Tasks.Task izmeniKorisnikaAsync(Administrator.ServiceAdministrator.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikaResponse")]
        Administrator.ServiceAdministrator.Korisnik vratiKorisnika(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikaResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> vratiKorisnikaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbine", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbineResponse")]
        Administrator.ServiceAdministrator.ListaPorudzbina vratiPorudzbine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbine", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbineResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaPorudzbina> vratiPorudzbineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbinu", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbinuResponse")]
        Administrator.ServiceAdministrator.Porudzbina vratiPorudzbinu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbinu", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbinuResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> vratiPorudzbinuAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOperaterChannel : Administrator.ServiceAdministrator.IServiceOperater, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOperaterClient : System.ServiceModel.ClientBase<Administrator.ServiceAdministrator.IServiceOperater>, Administrator.ServiceAdministrator.IServiceOperater {
        
        public ServiceOperaterClient() {
        }
        
        public ServiceOperaterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOperaterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOperaterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOperaterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Administrator.ServiceAdministrator.ListaKnjiga vratiKnjige() {
            return base.Channel.vratiKnjige();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKnjiga> vratiKnjigeAsync() {
            return base.Channel.vratiKnjigeAsync();
        }
        
        public Administrator.ServiceAdministrator.Knjiga vratiKnjigu(int id) {
            return base.Channel.vratiKnjigu(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Knjiga> vratiKnjiguAsync(int id) {
            return base.Channel.vratiKnjiguAsync(id);
        }
        
        public Administrator.ServiceAdministrator.Porudzbina poruciKnjigu(int id, int kolicina) {
            return base.Channel.poruciKnjigu(id, kolicina);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> poruciKnjiguAsync(int id, int kolicina) {
            return base.Channel.poruciKnjiguAsync(id, kolicina);
        }
        
        public Administrator.ServiceAdministrator.Korisnik login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public void dodajKnjigu(string autor, string naziv, double cena, int popust, int kolicina) {
            base.Channel.dodajKnjigu(autor, naziv, cena, popust, kolicina);
        }
        
        public System.Threading.Tasks.Task dodajKnjiguAsync(string autor, string naziv, double cena, int popust, int kolicina) {
            return base.Channel.dodajKnjiguAsync(autor, naziv, cena, popust, kolicina);
        }
        
        public void izmeniKnjigu(Administrator.ServiceAdministrator.Knjiga knjiga) {
            base.Channel.izmeniKnjigu(knjiga);
        }
        
        public System.Threading.Tasks.Task izmeniKnjiguAsync(Administrator.ServiceAdministrator.Knjiga knjiga) {
            return base.Channel.izmeniKnjiguAsync(knjiga);
        }
        
        public void dodajKorisnika(string username, string password) {
            base.Channel.dodajKorisnika(username, password);
        }
        
        public System.Threading.Tasks.Task dodajKorisnikaAsync(string username, string password) {
            return base.Channel.dodajKorisnikaAsync(username, password);
        }
        
        public Administrator.ServiceAdministrator.ListaKorisnika vratiKorisnike() {
            return base.Channel.vratiKorisnike();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKorisnika> vratiKorisnikeAsync() {
            return base.Channel.vratiKorisnikeAsync();
        }
        
        public void izmeniKorisnika(Administrator.ServiceAdministrator.Korisnik korisnik) {
            base.Channel.izmeniKorisnika(korisnik);
        }
        
        public System.Threading.Tasks.Task izmeniKorisnikaAsync(Administrator.ServiceAdministrator.Korisnik korisnik) {
            return base.Channel.izmeniKorisnikaAsync(korisnik);
        }
        
        public Administrator.ServiceAdministrator.Korisnik vratiKorisnika(int id) {
            return base.Channel.vratiKorisnika(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> vratiKorisnikaAsync(int id) {
            return base.Channel.vratiKorisnikaAsync(id);
        }
        
        public Administrator.ServiceAdministrator.ListaPorudzbina vratiPorudzbine() {
            return base.Channel.vratiPorudzbine();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaPorudzbina> vratiPorudzbineAsync() {
            return base.Channel.vratiPorudzbineAsync();
        }
        
        public Administrator.ServiceAdministrator.Porudzbina vratiPorudzbinu(int id) {
            return base.Channel.vratiPorudzbinu(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> vratiPorudzbinuAsync(int id) {
            return base.Channel.vratiPorudzbinuAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdministrator.IServiceAdministrator")]
    public interface IServiceAdministrator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjige", ReplyAction="http://tempuri.org/IService1/vratiKnjigeResponse")]
        Administrator.ServiceAdministrator.ListaKnjiga vratiKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjige", ReplyAction="http://tempuri.org/IService1/vratiKnjigeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKnjiga> vratiKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjigu", ReplyAction="http://tempuri.org/IService1/vratiKnjiguResponse")]
        Administrator.ServiceAdministrator.Knjiga vratiKnjigu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vratiKnjigu", ReplyAction="http://tempuri.org/IService1/vratiKnjiguResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Knjiga> vratiKnjiguAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/poruciKnjigu", ReplyAction="http://tempuri.org/IService1/poruciKnjiguResponse")]
        Administrator.ServiceAdministrator.Porudzbina poruciKnjigu(int id, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/poruciKnjigu", ReplyAction="http://tempuri.org/IService1/poruciKnjiguResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> poruciKnjiguAsync(int id, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        Administrator.ServiceAdministrator.Korisnik login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/dodajKnjiguResponse")]
        void dodajKnjigu(string autor, string naziv, double cena, int popust, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/dodajKnjiguResponse")]
        System.Threading.Tasks.Task dodajKnjiguAsync(string autor, string naziv, double cena, int popust, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKnjiguResponse")]
        void izmeniKnjigu(Administrator.ServiceAdministrator.Knjiga knjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKnjigu", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKnjiguResponse")]
        System.Threading.Tasks.Task izmeniKnjiguAsync(Administrator.ServiceAdministrator.Knjiga knjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/dodajKorisnikaResponse")]
        void dodajKorisnika(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/dodajKorisnikaResponse")]
        System.Threading.Tasks.Task dodajKorisnikaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnike", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikeResponse")]
        Administrator.ServiceAdministrator.ListaKorisnika vratiKorisnike();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnike", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKorisnika> vratiKorisnikeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKorisnikaResponse")]
        void izmeniKorisnika(Administrator.ServiceAdministrator.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/izmeniKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/izmeniKorisnikaResponse")]
        System.Threading.Tasks.Task izmeniKorisnikaAsync(Administrator.ServiceAdministrator.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikaResponse")]
        Administrator.ServiceAdministrator.Korisnik vratiKorisnika(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiKorisnika", ReplyAction="http://tempuri.org/IServiceOperater/vratiKorisnikaResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> vratiKorisnikaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbine", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbineResponse")]
        Administrator.ServiceAdministrator.ListaPorudzbina vratiPorudzbine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbine", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbineResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaPorudzbina> vratiPorudzbineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbinu", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbinuResponse")]
        Administrator.ServiceAdministrator.Porudzbina vratiPorudzbinu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiPorudzbinu", ReplyAction="http://tempuri.org/IServiceOperater/vratiPorudzbinuResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> vratiPorudzbinuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdministrator/obrisiKnjigu", ReplyAction="http://tempuri.org/IServiceAdministrator/obrisiKnjiguResponse")]
        void obrisiKnjigu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdministrator/obrisiKnjigu", ReplyAction="http://tempuri.org/IServiceAdministrator/obrisiKnjiguResponse")]
        System.Threading.Tasks.Task obrisiKnjiguAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdministrator/obrisiKorisnika", ReplyAction="http://tempuri.org/IServiceAdministrator/obrisiKorisnikaResponse")]
        void obrisiKorisnika(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdministrator/obrisiKorisnika", ReplyAction="http://tempuri.org/IServiceAdministrator/obrisiKorisnikaResponse")]
        System.Threading.Tasks.Task obrisiKorisnikaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdministrator/obrisiPorudzbinu", ReplyAction="http://tempuri.org/IServiceAdministrator/obrisiPorudzbinuResponse")]
        void obrisiPorudzbinu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdministrator/obrisiPorudzbinu", ReplyAction="http://tempuri.org/IServiceAdministrator/obrisiPorudzbinuResponse")]
        System.Threading.Tasks.Task obrisiPorudzbinuAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAdministratorChannel : Administrator.ServiceAdministrator.IServiceAdministrator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAdministratorClient : System.ServiceModel.ClientBase<Administrator.ServiceAdministrator.IServiceAdministrator>, Administrator.ServiceAdministrator.IServiceAdministrator {
        
        public ServiceAdministratorClient() {
        }
        
        public ServiceAdministratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAdministratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdministratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdministratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Administrator.ServiceAdministrator.ListaKnjiga vratiKnjige() {
            return base.Channel.vratiKnjige();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKnjiga> vratiKnjigeAsync() {
            return base.Channel.vratiKnjigeAsync();
        }
        
        public Administrator.ServiceAdministrator.Knjiga vratiKnjigu(int id) {
            return base.Channel.vratiKnjigu(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Knjiga> vratiKnjiguAsync(int id) {
            return base.Channel.vratiKnjiguAsync(id);
        }
        
        public Administrator.ServiceAdministrator.Porudzbina poruciKnjigu(int id, int kolicina) {
            return base.Channel.poruciKnjigu(id, kolicina);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> poruciKnjiguAsync(int id, int kolicina) {
            return base.Channel.poruciKnjiguAsync(id, kolicina);
        }
        
        public Administrator.ServiceAdministrator.Korisnik login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public void dodajKnjigu(string autor, string naziv, double cena, int popust, int kolicina) {
            base.Channel.dodajKnjigu(autor, naziv, cena, popust, kolicina);
        }
        
        public System.Threading.Tasks.Task dodajKnjiguAsync(string autor, string naziv, double cena, int popust, int kolicina) {
            return base.Channel.dodajKnjiguAsync(autor, naziv, cena, popust, kolicina);
        }
        
        public void izmeniKnjigu(Administrator.ServiceAdministrator.Knjiga knjiga) {
            base.Channel.izmeniKnjigu(knjiga);
        }
        
        public System.Threading.Tasks.Task izmeniKnjiguAsync(Administrator.ServiceAdministrator.Knjiga knjiga) {
            return base.Channel.izmeniKnjiguAsync(knjiga);
        }
        
        public void dodajKorisnika(string username, string password) {
            base.Channel.dodajKorisnika(username, password);
        }
        
        public System.Threading.Tasks.Task dodajKorisnikaAsync(string username, string password) {
            return base.Channel.dodajKorisnikaAsync(username, password);
        }
        
        public Administrator.ServiceAdministrator.ListaKorisnika vratiKorisnike() {
            return base.Channel.vratiKorisnike();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaKorisnika> vratiKorisnikeAsync() {
            return base.Channel.vratiKorisnikeAsync();
        }
        
        public void izmeniKorisnika(Administrator.ServiceAdministrator.Korisnik korisnik) {
            base.Channel.izmeniKorisnika(korisnik);
        }
        
        public System.Threading.Tasks.Task izmeniKorisnikaAsync(Administrator.ServiceAdministrator.Korisnik korisnik) {
            return base.Channel.izmeniKorisnikaAsync(korisnik);
        }
        
        public Administrator.ServiceAdministrator.Korisnik vratiKorisnika(int id) {
            return base.Channel.vratiKorisnika(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Korisnik> vratiKorisnikaAsync(int id) {
            return base.Channel.vratiKorisnikaAsync(id);
        }
        
        public Administrator.ServiceAdministrator.ListaPorudzbina vratiPorudzbine() {
            return base.Channel.vratiPorudzbine();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.ListaPorudzbina> vratiPorudzbineAsync() {
            return base.Channel.vratiPorudzbineAsync();
        }
        
        public Administrator.ServiceAdministrator.Porudzbina vratiPorudzbinu(int id) {
            return base.Channel.vratiPorudzbinu(id);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceAdministrator.Porudzbina> vratiPorudzbinuAsync(int id) {
            return base.Channel.vratiPorudzbinuAsync(id);
        }
        
        public void obrisiKnjigu(int id) {
            base.Channel.obrisiKnjigu(id);
        }
        
        public System.Threading.Tasks.Task obrisiKnjiguAsync(int id) {
            return base.Channel.obrisiKnjiguAsync(id);
        }
        
        public void obrisiKorisnika(int id) {
            base.Channel.obrisiKorisnika(id);
        }
        
        public System.Threading.Tasks.Task obrisiKorisnikaAsync(int id) {
            return base.Channel.obrisiKorisnikaAsync(id);
        }
        
        public void obrisiPorudzbinu(int id) {
            base.Channel.obrisiPorudzbinu(id);
        }
        
        public System.Threading.Tasks.Task obrisiPorudzbinuAsync(int id) {
            return base.Channel.obrisiPorudzbinuAsync(id);
        }
    }
}
